import pandas as pd
import matplotlib.pyplot as plt

def plot_rewards():

    df = pd.read_csv("monitor.csv", skiprows=1)  # generated by Monitor()
    rewards = df["r"]
    length = df["l"]

    plt.figure(figsize=(10,4))
    plt.plot(rewards, label="Episode Reward")
    plt.title("PPO Episode Rewards During Phase-3 Training")
    plt.grid(True)
    plt.xlabel("Episode")
    plt.ylabel("Reward")
    plt.legend()
    plt.show()

    plt.figure(figsize=(10,4))
    plt.plot(length, label="Episode Length")
    plt.title("Episode Length Curve")
    plt.grid(True)
    plt.xlabel("Episode")
    plt.ylabel("Steps")
    plt.legend()
    plt.show()


if __name__ == "__main__":
    plot_rewards()
